# Generated by Django 4.2.7 on 2024-01-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_favouriteproduct'),
        ('user', '0002_user_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourite',
            field=models.ManyToManyField(blank=True, to='shop.product'),
        ),
    ]
