# Generated by Django 4.2.7 on 2023-12-19 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='poduct_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='basket',
            name='user_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loyalty_program',
            name='user_added',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=10000),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
