# Generated by Django 4.2.7 on 2024-01-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_order_date_add_product_sold_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='loyalty_p',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='points',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=2000),
        ),
    ]
