# Generated by Django 4.2.7 on 2024-01-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_orderitem_loyalty_p_alter_product_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amount_rating',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
